### ISSUE TITLE
A new tagged release is needed

### ISSUE THREAD

**Issue by DxCat** [travoltron/laravel-preset-bootstrap4#7]
Currently (as of 24th November 2017),
running `composer require laravel-frontend-presets/bootstrap-4` as stated in the documentation will
give us the version 0.9.3 which contains zurb foundation stubs instead of the correct bootstrap 4 stubs.

https://github.com/laravel-frontend-presets/laravel-preset-bootstrap4/archive/0.9.3.zip

This of course will confuse new users of the package as the correct bootstrap 4 stubs is only available on the dev-master instead of the latest release.

**Comment by davenathanael** [comment]
@askaoru I'm wondering what do you mean by dev-master? Does it contains the right Bootstrap 4 stubs for auth views & welcome views? If it does, how can I access and update my project so that it has the right Bootstrap 4 stubs?

**Comment by DxCat** [comment]
@davenathanael 
Add this in your composer.json file `"laravel-frontend-presets/bootstrap-4": "dev-master",` and run `composer update`.

Doing it that way will get you the correct stubs.

**Comment by Francismori7** [comment]
Please tag, yeah

**Comment by travoltron** [comment]
Just tagged it. Thanks folks!
